# ============================================================================
#  Up 4evr — apply-settings.ps1   (Windows Module 1)
# ----------------------------------------------------------------------------
#  Applies the settings enabled in settings.conf, grouped by category with a
#  yes/no gate per group. Records each change into undo-settings.ps1 so the
#  run is reversible. Re-running is safe (already-correct settings are skipped).
#  Normally launched by apply-settings.bat, which elevates to Administrator.
#
#     -Yes       apply all enabled NON-danger settings without prompting
#     -DryRun    show what would change, do nothing
#  The DANGER category always requires typing DANGER to apply.
# ============================================================================
param([switch]$Yes, [switch]$DryRun)

. "$PSScriptRoot\settings-table.ps1"
$conf = Read-Conf "$PSScriptRoot\settings.conf"
$undo = "$PSScriptRoot\undo-settings.ps1"
$cats = @('power','ui','touch','services','updates','maintenance','danger')

Write-Host "Up 4evr - apply Windows settings" -ForegroundColor White
if ($DryRun) { Write-Host "(dry run - nothing will change)" -ForegroundColor DarkGray }

if (-not $DryRun -and -not (Test-Admin)) {
  Write-Host "Not running as Administrator - some settings will fail. Use apply-settings.bat." -ForegroundColor Yellow
}

# which enabled settings still need changing?
function Get-Pending($cat) {
  $Settings | Where-Object {
    $_.Cat -eq $cat -and $conf[$_.Key] -eq '1' -and
    -not ((Get-Cur $_.Check) -match $_.Desired)
  }
}

if (-not $DryRun) {
  @"
# Auto-generated by apply-settings.ps1 on $(Get-Date)
# Reverses the settings applied in that run (restores Windows defaults).
# Run as Administrator:  powershell -ExecutionPolicy Bypass -File undo-settings.ps1
. "`$PSScriptRoot\_helpers.ps1"

"@ | Set-Content -Path $undo -Encoding UTF8
}

$applied = 0
foreach ($cat in $cats) {
  $pending = @(Get-Pending $cat)
  if ($pending.Count -eq 0) { continue }

  Write-Host ("`n-- {0} --  ({1} to change)" -f $cat, $pending.Count) -ForegroundColor White
  foreach ($s in $pending) { Write-Host ("    - {0}" -f $s.Label) }

  $go = $false
  if ($DryRun) { $go = $true }
  elseif ($cat -eq 'danger') {
    $ans = Read-Host "  These reduce security. Type DANGER to apply, anything else to skip"
    if ($ans -eq 'DANGER') { $go = $true }
  }
  elseif ($Yes) { $go = $true }
  else {
    $ans = Read-Host ("  Apply these {0} settings? [y/N]" -f $cat)
    if ($ans -match '^(y|yes)$') { $go = $true }
  }
  if (-not $go) { Write-Host "  skipped" -ForegroundColor DarkGray; continue }

  foreach ($s in $pending) {
    if ($DryRun) { Write-Host ("  [would apply] {0}" -f $s.Label) -ForegroundColor Yellow; continue }

    $prior = Get-Cur $s.Check
    Add-Content $undo ("# {0}  (was: {1})" -f $s.Label, $prior)
    Add-Content $undo $s.Revert
    Add-Content $undo ""

    if ($s.Apply -eq '__INTERACTIVE__' -and $s.Key -eq 'auto_logon') {
      $u = Read-Host "    auto-logon username"
      $p = Read-Host "    auto-logon password (blank if none)"
      Set-Reg 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' 'AutoAdminLogon' String '1'
      Set-Reg 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' 'DefaultUserName' String $u
      if ($p) { Set-Reg 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' 'DefaultPassword' String $p }
    } else {
      try { Invoke-Expression $s.Apply } catch {}
    }

    $now = Get-Cur $s.Check
    if ($now -match $s.Desired) { Write-Host ("  [ done ] {0}" -f $s.Label) -ForegroundColor Green }
    else { Write-Host ("  [failed] {0}  (now: {1})" -f $s.Label, $now) -ForegroundColor Red }
    $applied++
  }
}

Write-Host ""
if ($DryRun) { Write-Host "Dry run complete." }
elseif ($applied -gt 0) {
  Write-Host ("Applied {0} setting(s). Undo written to {1}" -f $applied, $undo) -ForegroundColor White
  Write-Host "Revert with:  powershell -ExecutionPolicy Bypass -File undo-settings.ps1  (as Administrator)"
  Write-Host "Note: taskbar/Explorer changes take full effect after sign-out or restart." -ForegroundColor DarkGray
} else { Write-Host "Nothing to change - all enabled settings already correct." }
