#!/bin/bash
# ============================================================================
#  Up 4evr — apply-settings.sh   (Linux Module 1)
# ----------------------------------------------------------------------------
#  Applies the settings enabled in settings.conf, grouped by category with a
#  yes/no gate per group. Records the prior value and writes undo-settings.sh
#  so every change is reversible. Re-running is safe. Run inside your GNOME
#  session (gsettings needs it); root settings prompt for sudo once.
#
#     ./apply-settings.sh             interactive, per-category prompts
#     ./apply-settings.sh --yes       apply all enabled NON-danger settings
#     ./apply-settings.sh --dry-run   show what would change, do nothing
#  The DANGER category always requires typing DANGER.
# ============================================================================
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
source "$HERE/settings-table.sh"
[ -f "$HERE/settings.conf" ] && source "$HERE/settings.conf"

ASSUME_YES=0; DRY=0
case "${1:-}" in --yes) ASSUME_YES=1 ;; --dry-run) DRY=1 ;; esac

if [ -t 1 ]; then G=$'\033[32m'; Y=$'\033[33m'; R=$'\033[31m'; DIM=$'\033[2m'; B=$'\033[1m'; Z=$'\033[0m'
else G=""; Y=""; R=""; DIM=""; B=""; Z=""; fi

UNDO="$HERE/undo-settings.sh"
CATS="power ui performance updates danger"

pending_keys() {  # $1 = category
  local cat="$1" rec
  for rec in "${SETTINGS[@]}"; do
    IFS="$US" read -r KEY LABEL CAT SUDO CHECK DESIRED APPLY REVERT <<< "$rec"
    [ "$CAT" = "$cat" ] || continue
    local ev="SET_${KEY}"; [ "${!ev:-0}" = "1" ] || continue
    local cur; cur="$(bash -c "$CHECK" 2>/dev/null)"
    printf '%s' "$cur" | grep -Eq "$DESIRED" && continue
    echo "$rec"
  done
}

need_sudo_overall() {
  local cat rec
  for cat in $CATS; do
    while IFS= read -r rec; do
      [ -z "$rec" ] && continue
      IFS="$US" read -r KEY LABEL CAT SUDO CHECK DESIRED APPLY REVERT <<< "$rec"
      [ "$SUDO" = "1" ] && return 0
    done <<< "$(pending_keys "$cat")"
  done
  return 1
}

init_undo() {
  [ "$DRY" = "1" ] && return
  [ -f "$UNDO" ] && cp "$UNDO" "$UNDO.prev" 2>/dev/null
  {
    echo "#!/bin/bash"
    echo "# Auto-generated by apply-settings.sh on $(date)"
    echo "# Reverses the settings applied in that run (restores distro defaults)."
    echo "# Run:  bash undo-settings.sh   (sudo lines included where needed)"
    echo "set -u"; echo
  } > "$UNDO"
  chmod +x "$UNDO" 2>/dev/null
}

record_undo() {  # $1 label, $2 prior, $3 sudo, $4 revert
  [ "$DRY" = "1" ] && return
  {
    echo "# ${1}  (was: ${2:-<unset>})"
    if [ "$3" = "1" ]; then echo "sudo bash -c $(printf '%q' "$4")"; else echo "bash -c $(printf '%q' "$4")"; fi
    echo
  } >> "$UNDO"
}

apply_one() {  # $1 = record
  IFS="$US" read -r KEY LABEL CAT SUDO CHECK DESIRED APPLY REVERT <<< "$1"
  local prior; prior="$(bash -c "$CHECK" 2>/dev/null)"
  if [ "$DRY" = "1" ]; then printf "  %s[would apply]%s %s\n" "$Y" "$Z" "$LABEL"; return; fi
  record_undo "$LABEL" "$prior" "$SUDO" "$REVERT"
  if [ "$SUDO" = "1" ]; then sudo bash -c "$APPLY" >/dev/null 2>&1; else bash -c "$APPLY" >/dev/null 2>&1; fi
  local now; now="$(bash -c "$CHECK" 2>/dev/null)"
  if printf '%s' "$now" | grep -Eq "$DESIRED"; then printf "  %s[ done ]%s %s\n" "$G" "$Z" "$LABEL"
  else printf "  %s[failed]%s %s %s(now: %s)%s\n" "$R" "$Z" "$LABEL" "$DIM" "${now:-<empty>}" "$Z"; fi
}

printf "%sUp 4evr — apply Linux settings%s\n" "$B" "$Z"
[ "$DRY" = "1" ] && printf "%s(dry run — nothing will change)%s\n" "$DIM" "$Z"

if [ "$DRY" != "1" ] && need_sudo_overall; then
  printf "\nSome settings need root. You'll be asked for your password once.\n"
  sudo -v || { echo "Cannot get root; aborting."; exit 1; }
fi

init_undo
total_applied=0
for cat in $CATS; do
  recs="$(pending_keys "$cat")"
  [ -z "$recs" ] && continue
  count="$(printf '%s\n' "$recs" | grep -c .)"
  printf "\n%s── %s ──%s  (%d to change)\n" "$B" "$cat" "$Z" "$count"
  while IFS= read -r rec; do
    [ -z "$rec" ] && continue
    IFS="$US" read -r KEY LABEL CAT SUDO CHECK DESIRED APPLY REVERT <<< "$rec"
    printf "    • %s\n" "$LABEL"
  done <<< "$recs"

  go=0
  if [ "$DRY" = "1" ]; then go=1
  elif [ "$cat" = "danger" ]; then
    printf "%s  These reduce security. Type DANGER to apply, anything else to skip: %s" "$R" "$Z"
    read -r ans; [ "$ans" = "DANGER" ] && go=1
  elif [ "$ASSUME_YES" = "1" ]; then go=1
  else
    printf "  Apply these %s settings? [y/N] " "$cat"
    read -r ans; case "$ans" in y|Y|yes|YES) go=1 ;; esac
  fi
  if [ "$go" != "1" ]; then printf "  %sskipped%s\n" "$DIM" "$Z"; continue; fi

  while IFS= read -r rec; do
    [ -z "$rec" ] && continue
    apply_one "$rec"; total_applied=$((total_applied+1))
  done <<< "$recs"
done

echo
if [ "$DRY" = "1" ]; then printf "Dry run complete. Re-run without --dry-run to apply.\n"
elif [ "$total_applied" -gt 0 ]; then
  printf "%sApplied %d setting(s).%s Undo written to %s\n" "$B" "$total_applied" "$Z" "$UNDO"
  printf "Revert anytime with:  %sbash %s%s\n" "$B" "$UNDO" "$Z"
  printf "%sNote:%s some changes take full effect after logout or reboot.\n" "$DIM" "$Z"
else printf "Nothing to change — all enabled settings already correct.\n"; fi
